application:
  title: User Management API
  version: 1.0.0

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

aws:
  access:
    key: ${AWS_S3_ACCESS_KEY}
    secret: ${AWS_S3_SECRET}
  s3:
    bucketName: ${AWS_S3_BUCKET_NAME}
  ses:
    from: bruferper@gmail.com